version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: urban_advisor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: urban_advisor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/csv_data
    restart: unless-stopped

volumes:
  pgdata: